version: "3.8"

services:
  yii2_db:
    image: mysql:8.0
    container_name: yii2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: roblox.loc
    volumes:
      - yii2_db_data:/var/lib/mysql
    ports:
      - "3706:3306"
    networks:
      - yii2_network

  yii2_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii2_phpmyadmin
    restart: always
    environment:
      PMA_HOST: yii2_db
      PMA_USER: root
      PMA_PASSWORD: qwe123
    ports:
      - "8780:80"
    depends_on:
      - yii2_db
    networks:
      - yii2_network

  yii2_nginx:
    build:
      context: ./yii2
      dockerfile: ./nginx/Dockerfile
    container_name: yii2_nginx
    restart: always
    volumes:
      - ./yii2/app:/var/www/html
      - ./yii2/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8781:80"
    depends_on:
      - yii2_php
    networks:
      - yii2_network

  yii2_php:
    build:
      context: ./yii2
      dockerfile: ./php/Dockerfile
    container_name: yii2_php
    restart: always
    volumes:
      - ./yii2/app:/var/www/html
    expose:
      - "9000"
    networks:
      - yii2_network

networks:
  yii2_network:
    driver: bridge

volumes:
  yii2_db_data:
